# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryStub:
    """A deliberately plain gRPC service. It has no HTTP server, no JSON, and no
    knowledge of the web. The http annotations below are read by Envoy's
    grpc_json_transcoder to build a REST surface; the SERVICE never sees them.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItem = channel.unary_unary(
                '/legacy.inventory.v1.Inventory/GetItem',
                request_serializer=inventory__pb2.GetItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.Item.FromString,
                _registered_method=True)
        self.ListItems = channel.unary_unary(
                '/legacy.inventory.v1.Inventory/ListItems',
                request_serializer=inventory__pb2.ListItemsRequest.SerializeToString,
                response_deserializer=inventory__pb2.ListItemsResponse.FromString,
                _registered_method=True)
        self.ReserveStock = channel.unary_unary(
                '/legacy.inventory.v1.Inventory/ReserveStock',
                request_serializer=inventory__pb2.ReserveStockRequest.SerializeToString,
                response_deserializer=inventory__pb2.ReserveStockResponse.FromString,
                _registered_method=True)
        self.ResetStock = channel.unary_unary(
                '/legacy.inventory.v1.Inventory/ResetStock',
                request_serializer=inventory__pb2.ResetStockRequest.SerializeToString,
                response_deserializer=inventory__pb2.ResetStockResponse.FromString,
                _registered_method=True)
        self.CreateItem = channel.unary_unary(
                '/legacy.inventory.v1.Inventory/CreateItem',
                request_serializer=inventory__pb2.CreateItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.Item.FromString,
                _registered_method=True)
        self.DeleteItem = channel.unary_unary(
                '/legacy.inventory.v1.Inventory/DeleteItem',
                request_serializer=inventory__pb2.DeleteItemRequest.SerializeToString,
                response_deserializer=inventory__pb2.DeleteItemResponse.FromString,
                _registered_method=True)


class InventoryServicer:
    """A deliberately plain gRPC service. It has no HTTP server, no JSON, and no
    knowledge of the web. The http annotations below are read by Envoy's
    grpc_json_transcoder to build a REST surface; the SERVICE never sees them.
    """

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReserveStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetStock(self, request, context):
        """Puts every reservation back to zero so the demo can be run again from a
        known state. A collection-level verb, so the path has no {sku}.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateItem(self, request, context):
        """Writes a new item. POST to the collection is the REST idiom for create, and
        it is the same verb as :reserve - the suffix after the colon is what tells
        the transcoder which of the two POST routes a request belongs to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=inventory__pb2.GetItemRequest.FromString,
                    response_serializer=inventory__pb2.Item.SerializeToString,
            ),
            'ListItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListItems,
                    request_deserializer=inventory__pb2.ListItemsRequest.FromString,
                    response_serializer=inventory__pb2.ListItemsResponse.SerializeToString,
            ),
            'ReserveStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveStock,
                    request_deserializer=inventory__pb2.ReserveStockRequest.FromString,
                    response_serializer=inventory__pb2.ReserveStockResponse.SerializeToString,
            ),
            'ResetStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetStock,
                    request_deserializer=inventory__pb2.ResetStockRequest.FromString,
                    response_serializer=inventory__pb2.ResetStockResponse.SerializeToString,
            ),
            'CreateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateItem,
                    request_deserializer=inventory__pb2.CreateItemRequest.FromString,
                    response_serializer=inventory__pb2.Item.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=inventory__pb2.DeleteItemRequest.FromString,
                    response_serializer=inventory__pb2.DeleteItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'legacy.inventory.v1.Inventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('legacy.inventory.v1.Inventory', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inventory:
    """A deliberately plain gRPC service. It has no HTTP server, no JSON, and no
    knowledge of the web. The http annotations below are read by Envoy's
    grpc_json_transcoder to build a REST surface; the SERVICE never sees them.
    """

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legacy.inventory.v1.Inventory/GetItem',
            inventory__pb2.GetItemRequest.SerializeToString,
            inventory__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legacy.inventory.v1.Inventory/ListItems',
            inventory__pb2.ListItemsRequest.SerializeToString,
            inventory__pb2.ListItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReserveStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legacy.inventory.v1.Inventory/ReserveStock',
            inventory__pb2.ReserveStockRequest.SerializeToString,
            inventory__pb2.ReserveStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legacy.inventory.v1.Inventory/ResetStock',
            inventory__pb2.ResetStockRequest.SerializeToString,
            inventory__pb2.ResetStockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legacy.inventory.v1.Inventory/CreateItem',
            inventory__pb2.CreateItemRequest.SerializeToString,
            inventory__pb2.Item.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legacy.inventory.v1.Inventory/DeleteItem',
            inventory__pb2.DeleteItemRequest.SerializeToString,
            inventory__pb2.DeleteItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
